rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"


scrape_configs:
  - job_name: "spring_boot_solr_movies_search_service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["spring-boot-solr-movies-search-service:6060"]
    scrape_interval: 15s
  - job_name: "solr"
    metrics_path: "/solr/admin/metrics"
    params:
      wt: [ 'prometheus']
    static_configs:
      - targets: [ "solr:8983" ]
    scrape_interval: 15s
  - job_name: "spring_boot_solr_indexer"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "spring-boot-solr-indexer:8081" ]
    scrape_interval: 15s