spring:
  application:
    name: spring-boot-solr-indexer
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/}
      database: "sample_mflix"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "prometheus,metrics"
app:
  solr_url: ${SOLR_URL:http://localhost:8983/solr/movies}
  kafka_topic: ${KAFKA_INPUT_TOPIC:MOVIE.events}
  ollama_url: ${OLLAMA_URL:http://localhost:11434}
  semantic_search_enabled: ${SEMANTIC_SEARCH_ENABLED:false}