global:
  smtp_smarthost: 'mailpit:1025'
  smtp_from: 'search-platform@example.com'
  smtp_require_tls: false


route:
  group_by: ['service','severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-receiver'

  routes:
    - match:
        container_stats:  'spring_boot_solr_movies_search_service_cpu_usage'
      receiver: 'webhook-receiver'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

receivers:
  - name: 'email-receiver'
    email_configs:
      - to: 'support-team@example.com'
        send_resolved: true
        require_tls: false
        headers:
          subject: '[{{ .Status | toUpper }}] Service Alert: {{ .CommonLabels.alertname }}'
        html: '{{ template "email.custom" . }}'
  - name: 'webhook-receiver'
    webhook-configs:
      - url: 'http://rate-limit-service:5050/alerts'
        send_resolve: true