global:
  smtp_smarthost: 'mailpit:1025'
  smtp_from: 'search-platform@example.com'
  smtp_require_tls: false


route:
  group_by: ['service','severity']
  group_wait: 5s
  group_interval: 30s
  repeat_interval: 4h
  receiver: 'email-receiver'

  routes:
    - receiver: 'webhook-receiver'
      matchers:
        - container_stats =~ "spring_boot_mongodb_movies_service_cpu_usage|spring_boot_solr_movies_search_service_cpu_usage"



templates:
  - '/etc/alertmanager/templates/*.tmpl'

receivers:
  - name: 'email-receiver'
    email_configs:
      - to: 'support-team@example.com'
        send_resolved: true
        require_tls: false
        headers:
          subject: '[{{ .Status | toUpper }}] Service Alert: {{ .CommonLabels.alertname }}'
        html: '{{ template "email.custom" . }}'
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'http://rate-limit-service:5050/api/alerts'
        send_resolved: true