spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/}
      database: "sample_mflix"
    redis:
      url: redis://${VALKEY_HOST:localhost}:6379
  threads:
    virtual:
      enabled: true
management:
  server:
    port: 7070
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,health"
server:
  port: 7070