worker_processes auto;
events {
    worker_connections   8192;
    use epoll;
}

http {
    default_type  application/json;

    resolver 10.89.0.1 valid=5s;

    upstream spring_boot_mongodb_movies_service_pool{
        server spring-boot-mongodb-movies-service:7070;
        keepalive 1000;
        keepalive_requests 20000;
    }

    upstream spring_boot_solr_movies_search_service_pool{
        server spring-boot-solr-movies-search-service:6060;
        keepalive 1000;
        keepalive_requests 20000;
    }



    server {
        listen 80;
        set $target_backend "";

        location / {
            access_by_lua_block {
                local valkey = require "resty.redis";
                local val = valkey:new()

                val:set_timeout(1000)

                local ok, err = val:connect("valkey.dns.podman",6379)

                if not ok then
                    ngx.status = ngx.HTTP_INTERNAL_SERVER_ERROR
                    ngx.say('{"error": "Error while trying to connect to valkey: ' .. err .. '"}')
                    return ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
                end

                local context_path = ngx.var.uri

                local route_map = {}
                    route_map["/api/movies"] = "http://spring_boot_mongodb_movies_service_pool"
                    route_map["/api/movies/search"] = "http://spring_boot_solr_movies_search_service_pool"
                    route_map["/api/movies/semantic-search"] = "http://spring_boot_solr_movies_search_service_pool"
                    route_map["/api/movies/recommendations"] = "http://spring_boot_solr_movies_search_service_pool"


                local matched_backend_service = route_map[context_path]

                if matched_backend_service then

                     local valkey_keys_map = {}
                     valkey_keys_map["/api/movies"] = "spring_boot_mongodb_movies_service_high_cpu_usage"
                     valkey_keys_map["/api/movies/search"] = "spring_boot_solr_movies_search_service_high_cpu_usage"
                     valkey_keys_map["/api/movies/semantic-search"] = "spring_boot_solr_movies_search_service_high_cpu_usage"
                     valkey_keys_map["/api/movies/recommendations"] = "spring_boot_solr_movies_search_service_high_cpu_usage"


                    local matched_valkey_key = valkey_keys_map[context_path]

                    local res, err = val:get(matched_valkey_key)

                    if res and res ~= ngx.null and res == "true" then
                        ngx.status = 429
                        ngx.say('{"error": "Too Many Request for endpoint: ' .. context_path .. '"}')
                        val:set_keepalive(1000,200)
                        return ngx.exit(429)
                    end

                    ngx.var.target_backend = matched_backend_service

                else
                    ngx.status = 404
                    ngx.say('{"error": "The following path: ' .. context_path .. ' not found in API Gateway"}')
                    val:set_keepalive(1000,200)
                    return ngx.exit(404)
                end

                val:set_keepalive(10000,200)
            }
            proxy_pass $target_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_buffers 8 16k;
            proxy_buffer_size 16K;

            proxy_connect_timeout 10s;
            proxy_read_timeout 30s;
        }
    }
}
